# Generated by Django 3.0.1 on 2020-04-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0002_auto_20200413_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dim',
            name='image',
            field=models.ImageField(height_field='image_height', null=True, upload_to='documents/', verbose_name='', width_field='image_width'),
        ),
    ]
