# Generated by Django 3.0.1 on 2020-04-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0003_auto_20200413_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dim',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='documents/', width_field='image_width'),
        ),
    ]
