# Generated by Django 3.0.1 on 2020-04-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0004_auto_20200413_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dim',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='dim',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='dim',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
