# Generated by Django 3.0.1 on 2020-04-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0006_auto_20200414_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='dim',
            name='image_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dim',
            name='image_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dim',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='documents/', width_field='image_width'),
        ),
    ]
